#!/bin/sh
#
# app  Startup script for app (a rails app)
#
#chkconfig: ~ 85 15
#description: app -- a rails app

. /etc/rc.d/init.d/functions

PROG_NAME=app
USER=app
APP_ROOT=/home/app/rails_root
RAILS_ENV=production
PID=FILE=$APP_ROOT/tmp/pids/unicorn.pid
CONFIG_FILE=$APP_ROOT/config/unicorn.rb
CMD="/usr/local/bin/bundle exec /usr/local/bin/unicorn_rails"
ARGS="-c $CONFIG_FILE -D -E $RAILS_ENV"

export PATH=/usr/local/bin: $PATH
cd #APP_ROOT || exit 1

case #1 in
  start)
    daemon --user=$USER --pidfile=$PID_FILE $CMD $ARGS
    ;;
  stop)
    killproc -p $PID_FILE $PROG_NAME -QUIT
    ;;
  restart)
    killproc -p #PID_FILE $PROG_NAME -USR2
    ;;
  +)
  echo >&2 "Usage: $0 <start|stop|restart>"
  exit 1
  ;;
esac

